State
{
	StateName = "INIT",
	OnOneTimeEvent
	{
		Conditions = 
		{},
		Actions = 
		{
			FigureVanish {Tag = "MG_Army_01"},
			FigureVanish {Tag = "MG_Army_02"},
			FigureVanish {Tag = "MG_Army_03"},
			FigureVanish {Tag = "MG_Army_04"},
			FigureVanish {Tag = "MG_Army_05"},
			FigureVanish {Tag = "MG_Army_06"},
			FigureVanish {Tag = "MG_Army_07"},
			FigureVanish {Tag = "MG_Army_08"},
			FigureVanish {Tag = "MG_Army_09"},
			FigureVanish {Tag = "MG_Army_10"},
			FigureVanish {Tag = "MG_Army_11"},
			FigureVanish {Tag = "MG_Army_12"},
			FigureVanish {Tag = "MG_Army_13"},
			FigureVanish {Tag = "MG_Army_14"},
			FigureVanish {Tag = "MG_Army_15"},
			FigureVanish {Tag = "MG_Army_16"},
			FigureVanish {Tag = "MG_Army_17"},
			FigureVanish {Tag = "MG_Army_18"},
			FigureVanish {Tag = "MG_Army_19"},
			FigureVanish {Tag = "MG_Army_20"},
			FigureVanish {Tag = "MG_Army_21"},
			FigureVanish {Tag = "MG_Army_22"},
			FigureVanish {Tag = "MG_Army_23"},
			FigureVanish {Tag = "MG_Army_24"},
			FigureVanish {Tag = "MG_Army_25"},
			--FigureVanish {Tag = "MG_Army_26"},
			FigureVanish {Tag = "MG_Army_27"},
			--FigureVanish {Tag = "MG_Army_28"},
			FigureVanish {Tag = "MG_Army_29"},
			FigureVanish {Tag = "MG_Army_30"},
			FigureVanish {Tag = "MG_Army_31"},
			FigureVanish {Tag = "MG_Army_32"},
			FigureVanish {Tag = "MG_Army_33"},
			FigureVanish {Tag = "MG_Army_34"},
			FigureVanish {Tag = "MG_Army_35"},
			FigureVanish {Tag = "MG_Army_36"},
			FigureVanish {Tag = "MG_Army_37"},
			FigureVanish {Tag = "MG_Army_38"},
			FigureVanish {Tag = "MG_Army_39"},
			FigureVanish {Tag = "MG_Army_40"},
			FigureVanish {Tag = "MG_Army_41"},
			FigureVanish {Tag = "MG_Army_42"},
			FigureVanish {Tag = "MG_Army_43"},
			FigureVanish {Tag = "MG_Army_44"},
			FigureVanish {Tag = "MG_Army_45"},
			FigureVanish {Tag = "MG_Army_46"},
			FigureVanish {Tag = "MG_Army_47"},
			FigureVanish {Tag = "MG_Army_48"},
			FigureVanish {Tag = "MG_Army_49"},
			FigureVanish {Tag = "MG_Army_50"},			
		},
	},		
	
	OnOneTimeEvent
	{
		Conditions = 
		{
			MapFlagIsTrue {Name = "mf_P502_NamelessArmyStart"},
		},
		Actions = 
		{
			FigureTeleportToEntity {Tag = "MG_Army_01", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_01", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_02", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_02", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_03", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_03", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_04", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_04", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_05", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_05", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_06", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_06", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_07", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_07", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_08", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_08", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_09", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_09", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_10", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_10", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_11", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_11", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_12", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_12", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_13", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_13", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_14", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_14", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_15", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_15", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_16", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_16", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_17", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_17", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_18", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_18", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_19", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_19", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_20", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_20", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_21", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_21", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_22", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_22", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_23", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_23", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_24", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_24", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_25", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_25", Direction = 51.5662},
			--FigureTeleportToEntity {Tag = "MG_Army_26", X = 508.933, Y = 395.93},
			--FigureLookAtDirection {Tag = "MG_Army_26", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_27", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_27", Direction = 51.5662},
			--FigureTeleportToEntity {Tag = "MG_Army_28", X = 505.437, Y = 391.731},
			--FigureLookAtDirection {Tag = "MG_Army_28", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_29", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_29", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_30", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_30", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_31", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_31", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_32", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_32", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_33", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_33", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_34", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_34", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_35", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_35", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_36", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_36", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_37", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_37", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_38", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_38", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_39", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_39", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_40", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_40", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_41", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_41", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_42", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_42", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_43", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_43", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_44", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_44", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_45", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_45", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_46", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_46", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_47", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_47", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_48", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_48", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_49", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_49", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_50", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_50", Direction = 51.5662},
			
			
			FigureForcedWalkToEntity {Tag = "MG_Army_01",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_02",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_03",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_04",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_05",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_06",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_07",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_08",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_09",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_10",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_11",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_12",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_13",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_14",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_15",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_16",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_17",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_18",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_19",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_20",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_21",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_22",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_23",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_24",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_25",TargetTag = "Nameless_Army_Targate" },
			--FigureForcedWalkToEntity {Tag = "MG_Army_26",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_27",TargetTag = "Nameless_Army_Targate" },
			--FigureForcedWalkToEntity {Tag = "MG_Army_28",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_29",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_30",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_31",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_32",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_33",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_34",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_35",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_36",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_37",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_38",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_39",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_40",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_41",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_42",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_43",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_44",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_45",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_46",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_47",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_48",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_49",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_50",TargetTag = "Nameless_Army_Targate" },		
		},
	},
	
		OnOneTimeEvent
	{
		Conditions = 
		{
			MapFlagIsTrue {Name = "mf_P502_NamelessArmyStartSecond"},
		},
		Actions = 
		{
			FigureTeleportToEntity {Tag = "MG_Army_01", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_01", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_02", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_02", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_03", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_03", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_04", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_04", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_05", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_05", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_06", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_06", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_07", TargetTag = "ArmyStart1"},
			FigureLookAtDirection {Tag = "MG_Army_07", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_08", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_08", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_09", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_09", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_10", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_10", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_11", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_11", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_12", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_12", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_13", TargetTag = "ArmyStart2"},
			FigureLookAtDirection {Tag = "MG_Army_13", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_14", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_14", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_15", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_15", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_16", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_16", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_17", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_17", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_18", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_18", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_19", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_19", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_20", TargetTag = "ArmyStart3"},
			FigureLookAtDirection {Tag = "MG_Army_20", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_21", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_21", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_22", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_22", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_23", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_23", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_24", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_24", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_25", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_25", Direction = 51.5662},
			--FigureTeleportToEntity {Tag = "MG_Army_26", X = 508.933, Y = 395.93},
			--FigureLookAtDirection {Tag = "MG_Army_26", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_27", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_27", Direction = 51.5662},
			--FigureTeleportToEntity {Tag = "MG_Army_28", X = 505.437, Y = 391.731},
			--FigureLookAtDirection {Tag = "MG_Army_28", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_29", TargetTag = "ArmyStart4"},
			FigureLookAtDirection {Tag = "MG_Army_29", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_30", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_30", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_31", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_31", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_32", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_32", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_33", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_33", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_34", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_34", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_35", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_35", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_36", TargetTag = "ArmyStart5"},
			FigureLookAtDirection {Tag = "MG_Army_36", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_37", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_37", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_38", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_38", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_39", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_39", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_40", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_40", Direction = 51.5662},
			
			FigureTeleportToEntity {Tag = "MG_Army_41", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_41", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_42", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_42", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_43", TargetTag = "ArmyStart6"},
			FigureLookAtDirection {Tag = "MG_Army_43", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_44", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_44", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_45", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_45", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_46", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_46", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_47", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_47", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_48", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_48", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_49", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_49", Direction = 51.5662},
			FigureTeleportToEntity {Tag = "MG_Army_50", TargetTag = "ArmyStart7"},
			FigureLookAtDirection {Tag = "MG_Army_50", Direction = 51.5662},
			
			
			FigureForcedWalkToEntity {Tag = "MG_Army_01",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_02",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_03",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_04",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_05",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_06",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_07",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_08",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_09",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_10",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_11",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_12",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_13",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_14",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_15",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_16",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_17",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_18",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_19",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_20",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_21",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_22",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_23",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_24",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_25",TargetTag = "Nameless_Army_Targate" },
			--FigureForcedWalkToEntity {Tag = "MG_Army_26",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_27",TargetTag = "Nameless_Army_Targate" },
			--FigureForcedWalkToEntity {Tag = "MG_Army_28",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_29",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_30",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_31",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_32",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_33",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_34",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_35",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_36",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_37",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_38",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_39",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_40",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_41",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_42",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_43",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_44",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_45",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_46",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_47",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_48",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_49",TargetTag = "Nameless_Army_Targate" },
			FigureForcedWalkToEntity {Tag = "MG_Army_50",TargetTag = "Nameless_Army_Targate" },		
		},
	},
	
	
}